cc_binary(
    name = "server",
    srcs = ["server.cc"],
    deps = [
        "//core:core_lib",
    ],
)

cc_binary(
    name = "worker",
    srcs = ["worker.cc"],
    deps = [
        "//core:core_lib",
    ],
)
