cc_library(
    name = "core_lib",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//common-utils:reactor_lib",
        "//common-utils:threadpool_lib",
    ],
)

package(default_visibility = ["//visibility:public"]) 
